/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tour;

/**
 *
 * @author Jrad
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class flight extends javax.swing.JFrame {
    Connection con; // for establishing a connection
    Statement st;  //sql statement
    String cs;  //database path
    ResultSet rs; //for the resultset
    
    String user;  //database username
    String password;  //database password
    String query;
    /**
     * Creates new form flight
     */
    public flight() {
        st = null;
        //statement = null;
        rs = null;
        cs = "jdbc:mysql://localhost:3306/mydb";
        user = "root";
        password = "@tQbfjotlD//1q";
        initComponents();
        registerDriverAndst();
    }
    private void registerDriverAndst(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            st = con.createStatement();
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnfirst = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblflighname = new javax.swing.JLabel();
        lbldestiname = new javax.swing.JLabel();
        lbldepartureplace = new javax.swing.JLabel();
        lbldeparturedate = new javax.swing.JLabel();
        lblarrivaldate = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        txtflightname = new javax.swing.JTextField();
        txtdestinationplace = new javax.swing.JTextField();
        txtdepartureplace = new javax.swing.JTextField();
        txtdeparturedate = new javax.swing.JTextField();
        txtarrivaldate = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Flight registration");

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setText("UPDATE");

        btndel.setText("DELETE");

        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnfirst.setText("FIRST");
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        btnlast.setText("LAST");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        btnprevious.setText("PREVIOUS");
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        btnnext.setText("NEXT");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnnext)
                    .addComponent(btnfirst)
                    .addComponent(btnsave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlast, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnupdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnprevious, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnexit, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btndel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnclear))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnupdate)
                    .addComponent(btnclear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndel)
                    .addComponent(btnlast)
                    .addComponent(btnfirst))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprevious)
                    .addComponent(btnnext)
                    .addComponent(btnexit))
                .addGap(15, 15, 15))
        );

        lblflighname.setText("FLIGHT NAME");

        lbldestiname.setText("DESTINATION PLACE");

        lbldepartureplace.setText("DEPARTURE PLACE");

        lbldeparturedate.setText("DEPARTURE DATE");

        lblarrivaldate.setText("ARRIVAL DATE");

        lblprice.setText("PRICE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbldepartureplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldestiname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblflighname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldeparturedate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblarrivaldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblprice))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtflightname, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(txtdestinationplace)
                    .addComponent(txtdepartureplace)
                    .addComponent(txtdeparturedate)
                    .addComponent(txtarrivaldate)
                    .addComponent(txtprice))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblflighname)
                    .addComponent(txtflightname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldestiname)
                    .addComponent(txtdestinationplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldepartureplace)
                    .addComponent(txtdepartureplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldeparturedate)
                    .addComponent(txtdeparturedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblarrivaldate)
                    .addComponent(txtarrivaldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprice)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        
        
        if(txtflightname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the flight name");
            txtflightname.setText("");
            txtflightname.requestFocus();
            
        }
          if(txtdestinationplace.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the destination place");
            txtdestinationplace.setText("");
            txtdestinationplace.requestFocus();
            
        }
           if(txtdepartureplace.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the destination place");
            txtdepartureplace.setText("");
            txtdepartureplace.requestFocus();
            
        }
            if(txtdeparturedate.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the derpature date");
            txtdeparturedate.setText("");
            txtdeparturedate.requestFocus();
            
        }
             if(txtarrivaldate.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the arrival date");
            txtarrivaldate.setText("");
            txtarrivaldate.requestFocus();
            
        }
              if(txtprice.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the price of the flight");
            txtprice.setText("");
            txtprice.requestFocus();
            
        }
              String s1,s2,s3,s4,s5,s6;
              s1=txtflightname.getText();
              s2=txtdestinationplace.getText();
              s3=txtdepartureplace.getText();
              s4=txtdeparturedate.getText();
              s5=txtarrivaldate.getText();
              s6=txtprice.getText();
              
              try{
              query ="select licencenumber from driver";
              rs = st.executeQuery(query);
              while(rs.next()){
                  if(s6.equals(rs.getString("flightname"))){
                      JOptionPane.showMessageDialog(null, "the flight name already exists \nplease enter another flight name");
                      txtflightname.setText("");
                      txtflightname.requestFocus();
                  }
              }
              query = "INSERT INTO flight( flightname,destiname,departureplace,departuretime,arrivaldatetime,price)values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"')";
              JOptionPane.showConfirmDialog(null, "DO YOU REALLY WANT TO SAVE THE ABOVE INFORMATION");
              st.executeUpdate(query);
              txtflightname.setText("");
              txtdestinationplace.setText("");
              txtdepartureplace.setText("");
              txtdeparturedate.setText("");
              txtarrivaldate.setText("");
              txtprice.setText("");
              }
              catch(SQLException ex){
                  ex.printStackTrace();
              }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtflightname.setText("");
              txtdestinationplace.setText("");
              txtdepartureplace.setText("");
              txtdeparturedate.setText("");
              txtarrivaldate.setText("");
              txtprice.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
            
        
          JOptionPane.showConfirmDialog(null,"Do u really want to exit ");    
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
            
         try{
        query = "select flightname,destiname,departureplace,departuretime,arrivaldatetime,price from flight";
              
              rs=st.executeQuery(query);
              
              while(rs.next()){
                  if(rs.isFirst()){
                      txtflightname.setText(rs.getString("flightname"));
                 txtdestinationplace.setText(rs.getString("destiname"));
                 txtdepartureplace.setText(rs.getString("departureplace"));
                 txtdeparturedate.setText(rs.getString("departuretime"));
                 txtarrivaldate.setText(rs.getString("arrivaldatetime"));
                 txtprice.setText(rs.getString("price"));
                  }
              }
              
        }
        catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null,"there is no record at this position");
            txtflightname.setText("");
            txtflightname.requestFocus();
        }
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
       
         try{
        query = "select flightname,destiname,departureplace,departuretime,arrivaldatetime,price from flight";
              
              rs=st.executeQuery(query);
              
              while(rs.next()){
                  
                      txtflightname.setText(rs.getString("flightname"));
                 txtdestinationplace.setText(rs.getString("destiname"));
                 txtdepartureplace.setText(rs.getString("departureplace"));
                 txtdeparturedate.setText(rs.getString("departuretime"));
                 txtarrivaldate.setText(rs.getString("arrivaldatetime"));
                 txtprice.setText(rs.getString("price"));
                  
              }
              
        }
        catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null,"there is no record at this position");
            txtflightname.setText("");
            txtflightname.requestFocus();
        }
    }//GEN-LAST:event_btnlastActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
             try{
                 String s1 = txtflightname.getText();
                 query="SELECT flightid from flight where flightname='"+s1+"'";
                rs = st.executeQuery(query);
                 rs.next();
                 int i = rs.getInt(1);
                 int m = i+1;
        query = "select flightname,destiname,departureplace,departuretime,arrivaldatetime,price from flight where flightid='"+m+"'";
              rs=st.executeQuery(query);
              rs.next();
                 txtflightname.setText(rs.getString("flightname"));
                 txtdestinationplace.setText(rs.getString("destiname"));
                 txtdepartureplace.setText(rs.getString("departureplace"));
                 txtdeparturedate.setText(rs.getString("departuretime"));
                 txtarrivaldate.setText(rs.getString("arrivaldatetime"));
                 txtprice.setText(rs.getString("price"));
                  
              
              
        }
        catch(SQLException ex){
           
            JOptionPane.showMessageDialog(null,"there is no record at this position");
            txtflightname.setText("");
            txtdestinationplace.setText("");
              txtdepartureplace.setText("");
              txtdeparturedate.setText("");
              txtarrivaldate.setText("");
              txtprice.setText("");
            txtflightname.requestFocus();
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        try{
                 String s1 = txtflightname.getText();
                 query="SELECT flightid from flight where flightname='"+s1+"'";
                 rs = st.executeQuery(query);
                 rs.next();
                 int i = rs.getInt("flightid");
                 int m = i-1;
        query = "select flightname,destiname,departureplace,departuretime,arrivaldatetime,price from flight where flightid='"+m+"'";
              rs=st.executeQuery(query);
              rs.next();
                 txtflightname.setText(rs.getString("flightname"));
                 txtdestinationplace.setText(rs.getString("destiname"));
                 txtdepartureplace.setText(rs.getString("departureplace"));
                 txtdeparturedate.setText(rs.getString("departuretime"));
                 txtarrivaldate.setText(rs.getString("arrivaldatetime"));
                 txtprice.setText(rs.getString("price"));
                  
              
              
        }
        catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null,"there is no record at this position");
            txtflightname.setText("");
            txtdestinationplace.setText("");
              txtdepartureplace.setText("");
              txtdeparturedate.setText("");
              txtarrivaldate.setText("");
              txtprice.setText("");
            txtflightname.requestFocus();
        }
    }//GEN-LAST:event_btnpreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Flight() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblarrivaldate;
    private javax.swing.JLabel lbldeparturedate;
    private javax.swing.JLabel lbldepartureplace;
    private javax.swing.JLabel lbldestiname;
    private javax.swing.JLabel lblflighname;
    private javax.swing.JLabel lblprice;
    private javax.swing.JTextField txtarrivaldate;
    private javax.swing.JTextField txtdeparturedate;
    private javax.swing.JTextField txtdepartureplace;
    private javax.swing.JTextField txtdestinationplace;
    private javax.swing.JTextField txtflightname;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
