/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tour;

/**
 *
 * @author Jrad
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class promotion extends javax.swing.JFrame {
    Connection con; // for establishing a connection
    Statement st;  //sql statement
    String cs;  //database path
    ResultSet rs; //for the resultset
    
    String user;  //database username
    String password;  //database password
    String query;
    /**
     * Creates new form promotion
     */
    public promotion() {
        st = null;
        //statement = null;
        rs = null;
        cs = "jdbc:mysql://localhost:3306/mydb";
        user = "root";
        password = "@tQbfjotlD//1q";
        initComponents();
        registerDriverAndst();
    }
    private void registerDriverAndst(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            st = con.createStatement();
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblpromotionname = new javax.swing.JLabel();
        lbldescription = new javax.swing.JLabel();
        lbldiscount = new javax.swing.JLabel();
        lblenddate = new javax.swing.JLabel();
        txtpromotioname = new javax.swing.JTextField();
        txtdescription = new javax.swing.JTextField();
        txtdiscount = new javax.swing.JTextField();
        txtenddate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnfirst = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        panel6 = new java.awt.Panel();
        lbltitle4 = new java.awt.Label();
        panel12 = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblpromotionname.setText("PROMOTION NAME");

        lbldescription.setText("DESCRIPTION");

        lbldiscount.setText("DISCOUNT");

        lblenddate.setText("END DATE");

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setText("UPDATE");

        btndel.setText("DELETE");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnfirst.setText("FIRST");
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        btnlast.setText("LAST");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        btnprevious.setText("PREVIOUS");
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        btnnext.setText("NEXT");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnnext)
                    .addComponent(btnfirst)
                    .addComponent(btnsave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlast, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnupdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnprevious, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnexit, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btndel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnclear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnupdate)
                    .addComponent(btnclear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndel)
                    .addComponent(btnlast)
                    .addComponent(btnfirst))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprevious)
                    .addComponent(btnnext)
                    .addComponent(btnexit))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpromotionname, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbldescription, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(lbldiscount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblenddate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpromotioname)
                            .addComponent(txtenddate)
                            .addComponent(txtdiscount)
                            .addComponent(txtdescription))))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpromotionname)
                    .addComponent(txtpromotioname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldescription)
                    .addComponent(txtdescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldiscount)
                    .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblenddate)
                    .addComponent(txtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        panel6.setBackground(new java.awt.Color(0, 51, 0));

        lbltitle4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lbltitle4.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle4.setText("GERALD TOURS AND TRAVEL");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tour/R1.jpg"))); // NOI18N

        javax.swing.GroupLayout panel12Layout = new javax.swing.GroupLayout(panel12);
        panel12.setLayout(panel12Layout);
        panel12Layout.setHorizontalGroup(
            panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel12Layout.setVerticalGroup(
            panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        if(txtpromotioname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the promotion name");
            txtpromotioname.requestFocus();
        }
        if(txtdescription.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the description of the promotion");
            txtdescription.requestFocus();
        }
        if(txtdiscount.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the discount");
            txtdiscount.requestFocus();
        }
        if(txtenddate.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the end date");
            txtenddate.requestFocus();
        }
        
        String s1,s2,s3,s4;
        s1=txtpromotioname.getText();
        s2 = txtdescription.getText();
        s3 = txtdiscount.getText();
        s4 = txtenddate.getText();
        
        try{
        query = "Insert into promotions (promotioname,decription,discount,endDate) va;ues('"+s1+"','"+s2+"','"+s3+"','"+s4+"'";
        JOptionPane.showConfirmDialog(null, "Do you really want to save the above information");
        st.executeUpdate(query);
        JOptionPane.showMessageDialog(null,"promoton added");
        }
        catch(SQLException ex){
             JOptionPane.showMessageDialog(null,"promoton already exists");
             txtpromotioname.setText("");
             txtdescription.setText("");
             txtdiscount.setText("");
             txtenddate.setText("");
             txtpromotioname.requestFocus();
        }
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
        
        
        String s1,s2,s3,s4;
        s1=txtpromotioname.getText();
        s2 = txtdescription.getText();
        s3 = txtdiscount.getText();
        s4 = txtenddate.getText();
        
        try{
        query = "select promotioname,decription,discount,endDate from promotions";
        rs = st.executeQuery(query);
        while(rs.next()){
            if(rs.isFirst()){
                txtpromotioname.setText(rs.getString("promotioname"));
                txtdescription.setText(rs.getString("decription"));
                txtdiscount.setText(rs.getString("discount"));
                txtenddate.setText(rs.getString("endDate"));
                
            }
        }
        }
        catch(SQLException ex){
            
             JOptionPane.showMessageDialog(null,"the record here doesn't exist");
             txtpromotioname.setText("");
             txtdescription.setText("");
             txtdiscount.setText("");
             txtenddate.setText("");
             txtpromotioname.requestFocus();
        }
        
        
        
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
      
        
        String s1,s2,s3,s4;
        s1=txtpromotioname.getText();
        s2 = txtdescription.getText();
        s3 = txtdiscount.getText();
        s4 = txtenddate.getText();
        
        try{
        query = "select promotioname,decription,discount,endDate from promotions";
        rs = st.executeQuery(query);
        while(rs.next()){
            if(rs.isLast()){
                txtpromotioname.setText(rs.getString("promotioname"));
                txtdescription.setText(rs.getString("decription"));
                txtdiscount.setText(rs.getString("discount"));
                txtenddate.setText(rs.getString("endDate"));
                
            }
        }
        }
        catch(SQLException ex){
             JOptionPane.showMessageDialog(null,"the record here doesn't exist");
             txtpromotioname.setText("");
             txtdescription.setText("");
             txtdiscount.setText("");
             txtenddate.setText("");
             txtpromotioname.requestFocus();
        }
        
    }//GEN-LAST:event_btnlastActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
       if(txtpromotioname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the promotion name");
            txtpromotioname.requestFocus();
        }
        if(txtdescription.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the description of the promotion");
            txtdescription.requestFocus();
        }
        if(txtdiscount.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the discount");
            txtdiscount.requestFocus();
        }
        if(txtenddate.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the end date");
            txtenddate.requestFocus();
        }
        
        String s1,s2,s3,s4;
        s1=txtpromotioname.getText();
        s2 = txtdescription.getText();
        s3 = txtdiscount.getText();
        s4 = txtenddate.getText();
        
        try{
            query="select promotionid from promotions where promotioname='"+s1+"'";
            rs =st.executeQuery(query);
            rs.next();
            int i = rs.getInt("promotionid");
            
            int m = i+1;
        query = "select promotioname,decription,discount,endDate from promotions where promotionid='"+m+"'";
        rs = st.executeQuery(query);
        rs.next();
        txtpromotioname.setText(rs.getString("promotioname"));
        txtdescription.setText(rs.getString("decription"));
        txtdiscount.setText(rs.getString("discount"));
        txtenddate.setText(rs.getString("endDate"));
 
        }
        catch(SQLException ex){
             JOptionPane.showMessageDialog(null,"the record here doesn't exist");
             txtpromotioname.setText("");
             txtdescription.setText("");
             txtdiscount.setText("");
             txtenddate.setText("");
             txtpromotioname.requestFocus();
        }
        
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        if(txtpromotioname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the promotion name");
            txtpromotioname.requestFocus();
        }
        if(txtdescription.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the description of the promotion");
            txtdescription.requestFocus();
        }
        if(txtdiscount.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the discount");
            txtdiscount.requestFocus();
        }
        if(txtenddate.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the end date");
            txtenddate.requestFocus();
        }
        
        String s1,s2,s3,s4;
        s1=txtpromotioname.getText();
        s2 = txtdescription.getText();
        s3 = txtdiscount.getText();
        s4 = txtenddate.getText();
        
        try{
            query="select promotionid from promotions where promotioname='"+s1+"'";
            rs =st.executeQuery(query);
            rs.next();
            int i = rs.getInt("promotionid");
            
            int m = i-1;
        query = "select promotioname,decription,discount,endDate from promotions where promotionid='"+m+"'";
        rs = st.executeQuery(query);
        rs.next();
        txtpromotioname.setText(rs.getString("promotioname"));
        txtdescription.setText(rs.getString("decription"));
        txtdiscount.setText(rs.getString("discount"));
        txtenddate.setText(rs.getString("endDate"));
 
        }
        catch(SQLException ex){
             JOptionPane.showMessageDialog(null,"the record here doesn't exist");
             txtpromotioname.setText("");
             txtdescription.setText("");
             txtdiscount.setText("");
             txtenddate.setText("");
             txtpromotioname.requestFocus();
        }
        
    }//GEN-LAST:event_btnpreviousActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed

        
               JOptionPane.showConfirmDialog(null,"Do u really want to exit ");    
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtpromotioname.setText("");
             txtdescription.setText("");
             txtdiscount.setText("");
             txtenddate.setText("");
             txtpromotioname.requestFocus();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
       if(txtpromotioname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the promotion name");
            txtpromotioname.requestFocus();
        }
       
       String s1 =txtpromotioname.getText();
       try{
       query = "select promotioname from promotions";
       rs = st.executeQuery(query);
       while(rs.next()){
           if(s1.equals(rs.getString("promotioname"))){
               query = "delete from promotions where promotioname='"+s1+"'";
               JOptionPane.showConfirmDialog(null,"Do you really want to delete the promotion");
               st.executeUpdate(query);
           }
       }
       }
       catch(SQLException ex){
           JOptionPane.showMessageDialog(null,"the promotion doesn't exist please try writing another promotion name");
           txtpromotioname.setText("");
             txtdescription.setText("");
             txtdiscount.setText("");
             txtenddate.setText("");
             txtpromotioname.requestFocus();
       }
    }//GEN-LAST:event_btndelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(promotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(promotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(promotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(promotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new promotion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbldescription;
    private javax.swing.JLabel lbldiscount;
    private javax.swing.JLabel lblenddate;
    private javax.swing.JLabel lblpromotionname;
    private java.awt.Label lbltitle4;
    private java.awt.Panel panel12;
    private java.awt.Panel panel6;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtenddate;
    private javax.swing.JTextField txtpromotioname;
    // End of variables declaration//GEN-END:variables
}
