/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tour;

/**
 *
 * @author Jrad
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class room extends javax.swing.JFrame {
    Connection con; // for establishing a connection
    Statement st;  //sql statement
    String cs;  //database path
    ResultSet rs; //for the resultset
    
    String user;  //database username
    String password;  //database password
    String query;
    /**
     * Creates new form room
     */
    public room() {
        st = null;
        //statement = null;
        rs = null;
        cs = "jdbc:mysql://localhost:3306/mydb";
        user = "root";
        password = "@tQbfjotlD//1q";
        initComponents();
        registerDriverAndst();
    }
    private void registerDriverAndst(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            st = con.createStatement();
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnfirst = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtroomname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        lblroomname = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        lblhotel = new javax.swing.JLabel();
        txthotelname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rooms available");
        setBackground(new java.awt.Color(255, 51, 0));

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setText("UPDATE");

        btndel.setText("DELETE");

        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnfirst.setText("FIRST");
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        btnlast.setText("LAST");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        btnprevious.setText("PREVIOUS");
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        btnnext.setText("NEXT");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnnext)
                    .addComponent(btnfirst)
                    .addComponent(btnsave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlast, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnupdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnprevious, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnexit, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btndel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnclear))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnupdate)
                    .addComponent(btnclear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndel)
                    .addComponent(btnlast)
                    .addComponent(btnfirst))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprevious)
                    .addComponent(btnnext)
                    .addComponent(btnexit))
                .addGap(15, 15, 15))
        );

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        lblroomname.setText("ROOM NAME");

        lblprice.setText("PRICE");

        lblhotel.setText("HOTEL NAME");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblprice, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblroomname, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblhotel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtroomname, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(txtprice)
                    .addComponent(txthotelname))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtroomname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblroomname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprice)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhotel)
                    .addComponent(txthotelname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        if(txtroomname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the room name");
            txtroomname.setText("");
            txtroomname.requestFocus();
        }
        if(txthotelname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the hotel name");
            txthotelname.setText("");
            txthotelname.requestFocus();
        }
        if(txtprice.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the price of the room");
            txtprice.setText("");
            txtprice.requestFocus();
        }
        String s1,s2,s3;
        s1 = txtroomname.getText();
        s2 = txthotelname.getText();
        s3 = txtprice.getText();
        try{
        query = "select RoomName from room";
        rs = st.executeQuery(query);
        while(rs.next()){
            if(s1.equals(rs.getString("RoomName"))){
                JOptionPane.showMessageDialog(null,"the room name already exists");
                txtroomname.setText("");
                txtroomname.requestFocus();
            }
        }
        
        query = "select idHotel from hotel where HotelName='"+s2+"'";
        rs = st.executeQuery(query);
        rs.next();
        int i = rs.getInt("idHotel");
        
        query = "insert into room (RoomName,Price,Hotel_idHotel) values ('"+s1+"','"+s3+"','"+s1+"'";
        JOptionPane.showConfirmDialog(null,"do you really want to add the above information");
        st.executeUpdate(query);
        JOptionPane.showMessageDialog(null,"record added");
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"p;ease check your information and try again \n Thanks");
            txtroomname.setText("");
            txthotelname.setText("");
            txtprice.setText("");
            txtroomname.requestFocus();
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
      
        String s1,s2,s3;
        s1 = txtroomname.getText();
        s2 = txthotelname.getText();
        s3 = txtprice.getText();
        try{
        
        
        query = "select RoomName,Price,Hotel_idHotel from room";
        rs = st.executeQuery(query);
        while(rs.next()){
            if(rs.isFirst()){
                txtroomname.setText(rs.getString("RoomName"));
                txtprice.setText(rs.getString("Price"));
                int i = rs.getInt("Hotel_idHotel");
                
                query = "select HotelName from hotel where idHotel='"+i+"'";
                rs = st.executeQuery(query);
                rs.next();
                txthotelname.setText(rs.getString("HotelName"));
            }
        }
        
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"there is no record at this position");
            txtroomname.setText("");
            txthotelname.setText("");
            txtprice.setText("");
            txtroomname.requestFocus();
        }
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        String s1,s2,s3;
        s1 = txtroomname.getText();
        s2 = txthotelname.getText();
        s3 = txtprice.getText();
        try{
               
        query = "select RoomName,Price,Hotel_idHotel from room";
        rs = st.executeQuery(query);
        while(rs.next()){
            if(rs.isLast()){
                txtroomname.setText(rs.getString("RoomName"));
                txtprice.setText(rs.getString("Price"));
                int i = rs.getInt("Hotel_idHotel");
                
                query = "select HotelName from hotel where idHotel='"+i+"'";
                rs = st.executeQuery(query);
                rs.next();
                txthotelname.setText(rs.getString("HotelName"));
            }
        }
        
        }
        catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null,"there is no record at this position");
            txtroomname.setText("");
            txthotelname.setText("");
            txtprice.setText("");
            txtroomname.requestFocus();
        }
    }//GEN-LAST:event_btnlastActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
            String s1,s2,s3;
        s1 = txtroomname.getText();
        s2 = txthotelname.getText();
        s3 = txtprice.getText();
        try{
        query = "Select idRoom from room where RoomName='"+s1+"'";
        rs = st.executeQuery(query);
        rs.next();
        int i = rs.getInt("idRoom");
        
        int m = i+1;
        query = "select RoomName,Price,Hotel_idHotel from room where idRoom='"+m+"'";
        rs = st.executeQuery(query);
        rs.next();
        txtroomname.setText(rs.getString("RoomName"));
        txtprice.setText(rs.getString("Price"));
        int k = rs.getInt("Hotel_idHotel");
        query = "select HotelName from hotel where idHotel='"+k+"'";
        rs = st.executeQuery(query);
        rs.next();
        txthotelname.setText(rs.getString("HotelName"));
            
        
        
        }
        catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null,"there is no record at this position");
            txtroomname.setText("");
            txthotelname.setText("");
            txtprice.setText("");
            txtroomname.requestFocus();
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        
        String s1,s2,s3;
        s1 = txtroomname.getText();
        s2 = txthotelname.getText();
        s3 = txtprice.getText();
        try{
        query = "Select idRoom from room where RoomName='"+s1+"'";
        rs = st.executeQuery(query);
        rs.next();
        int i = rs.getInt("idRoom");
        
        int m = i-1;
        query = "select RoomName,Price,Hotel_idHotel from room where idRoom='"+m+"'";
        rs = st.executeQuery(query);
        rs.next();
        txtroomname.setText(rs.getString("RoomName"));
        txtprice.setText(rs.getString("Price"));
        int k = rs.getInt("Hotel_idHotel");
        query = "select HotelName from hotel where idHotel='"+k+"'";
        rs = st.executeQuery(query);
        rs.next();
        txthotelname.setText(rs.getString("HotelName"));
            
        
        
        }
        catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null,"there is no record at this position");
            txtroomname.setText("");
            txthotelname.setText("");
            txtprice.setText("");
            txtroomname.requestFocus();
        }
    }//GEN-LAST:event_btnpreviousActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        
        JOptionPane.showConfirmDialog(null,"Do u really want to exit ");    
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed

        txtroomname.setText("");
            txthotelname.setText("");
            txtprice.setText("");
            txtroomname.requestFocus();
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Room() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblhotel;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblroomname;
    private javax.swing.JTextField txthotelname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtroomname;
    // End of variables declaration//GEN-END:variables
}
