/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tour;

/**
 *
 * @author Jrad
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class vehicle extends javax.swing.JFrame {
    Connection con; // for establishing a connection
    Statement st;  //sql statement
    String cs;  //database path
    ResultSet rs; //for the resultset
    
    String user;  //database username
    String password;  //database password
    String query;
    /**
     * Creates new form vehicle
     */
    public vehicle() {
        st = null;
        //statement = null;
        rs = null;
        cs = "jdbc:mysql://localhost:3306/mydb";
        user = "root";
        password = "@tQbfjotlD//1q";
        initComponents();
        registerDriverAndst();
    }
    private void registerDriverAndst(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            st = con.createStatement();
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnfirst = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtlicencenumber = new javax.swing.JTextField();
        txtvehiclename = new javax.swing.JTextField();
        lbllicencenumber = new javax.swing.JLabel();
        lblvehiclename = new javax.swing.JLabel();
        lbltour = new javax.swing.JLabel();
        txttourname = new javax.swing.JTextField();
        lbldrivername = new javax.swing.JLabel();
        txtdrivername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setText("UPDATE");

        btndel.setText("DELETE");

        btnexit.setText("EXIT");

        btnfirst.setText("FIRST");
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        btnlast.setText("LAST");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        btnprevious.setText("PREVIOUS");

        btnnext.setText("NEXT");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnclear.setText("CLEAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnnext)
                    .addComponent(btnfirst)
                    .addComponent(btnsave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlast, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnupdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnprevious, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnexit, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btndel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnclear))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnupdate)
                    .addComponent(btnclear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndel)
                    .addComponent(btnlast)
                    .addComponent(btnfirst))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprevious)
                    .addComponent(btnnext)
                    .addComponent(btnexit))
                .addGap(15, 15, 15))
        );

        txtvehiclename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehiclenameActionPerformed(evt);
            }
        });

        lbllicencenumber.setText("LICENCE NUMBER");

        lblvehiclename.setText("VEHICLE NAME");

        lbltour.setText("TOUR NAME");

        lbldrivername.setText("DRIVER NAME");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblvehiclename, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(lbllicencenumber, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(lbltour, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldrivername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttourname)
                    .addComponent(txtlicencenumber, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(txtvehiclename)
                    .addComponent(txtdrivername))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlicencenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllicencenumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvehiclename)
                    .addComponent(txtvehiclename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltour)
                    .addComponent(txttourname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldrivername)
                    .addComponent(txtdrivername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtvehiclenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehiclenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehiclenameActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        if(txtvehiclename.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the vehicle name");
            txtvehiclename.setText("");
            txtvehiclename.requestFocus();
        }
        if(txtlicencenumber.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the vehicle's licence number");
            txtlicencenumber.setText("");
            txtlicencenumber.requestFocus();
        }
        if(txttourname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the tour name \nwhere the vehicle has moved to");
            txttourname.setText("");
            txttourname.requestFocus();
        }
        if(txtdrivername.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the driver's name");
            txtdrivername.setText("");
            txtdrivername.requestFocus();
        }
        String s1,s2,s3,s4;
        s1 = txtvehiclename.getText();
        s2 = txtlicencenumber.getText();
        s3 = txttourname.getText();
        s4 = txtdrivername.getText();
        try{
        query = "select licencenumber from vehicle";
        rs = st.executeQuery(query);
        while(rs.next()){
            if(s2.equals(rs.getString("RoomName"))){
                JOptionPane.showMessageDialog(null,"the vehicle already exists \n please try entering another vehicle or delete the above vehicle");
                txtlicencenumber.setText("");
                txtlicencenumber.requestFocus();
            }
        }
        
        query = "select tourid from tour where tourname='"+s3+"'";
        rs = st.executeQuery(query);
        rs.next();
        int i = rs.getInt("tourid");
        
        query = "select driverid from driver where firstname='"+s4+"'";
        rs = st.executeQuery(query);
        rs.next();
        int m = rs.getInt("driverid");
        
        query = "insert into vehicle (licencenumber,vehiclename,tour_tourid,driver_driverid) values ('"+s1+"','"+s2+"','"+i+"','"+m+"'";
        JOptionPane.showConfirmDialog(null,"do you really want to add the above information");
        st.executeUpdate(query);
        JOptionPane.showMessageDialog(null,"record added");
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"p;ease check your information and try again \n Thanks");
            txtlicencenumber.setText("");
            txtvehiclename.setText("");
            txttourname.setText("");
            txtdrivername.setText("");
            txtlicencenumber.requestFocus();
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
       
        try{
        query = "select licencenumber,vehiclename,tour_tourid,driver_driverid from vehicle";
        rs = st.executeQuery(query);
        while(rs.next()){
            if(rs.isFirst()){
                txtlicencenumber.setText(rs.getString("licencenumber"));
                txtvehiclename.setText(rs.getString("vehiclename"));
                int i = rs.getInt("tour_tourid");
                int m = rs.getInt("driver_driverid");
                
                query = "select tourname from tour where tourid='"+i+"'";
                rs = st.executeQuery(query);
                rs.next();
                txttourname.setText(rs.getString("tourname"));
        
                query = "select firstname from driver where driverid='"+m+"'";
                rs = st.executeQuery(query);
                rs.next();
                txtdrivername.setText(rs.getString("firstname"));
            }
        }
        }
        catch(SQLException ex){
                ex.printStackTrace();
                }
        
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
         try{
        query = "select licencenumber,vehiclename,tour_tourid,driver_driverid from vehicle";
        rs = st.executeQuery(query);
        while(rs.next()){
            if(rs.isLast()){
                txtlicencenumber.setText(rs.getString("licencenumber"));
                txtvehiclename.setText(rs.getString("vehiclename"));
                int i = rs.getInt("tour_tourid");
                int m = rs.getInt("driver_driverid");
                
                query = "select tourname from tour where tourid='"+i+"'";
                rs = st.executeQuery(query);
                rs.next();
                txttourname.setText(rs.getString("tourname"));
        
                query = "select firstname from driver where driverid='"+m+"'";
                rs = st.executeQuery(query);
                rs.next();
                txtdrivername.setText(rs.getString("firstname"));
            }
        }
        }
        catch(SQLException ex){
                ex.printStackTrace();
                }
    }//GEN-LAST:event_btnlastActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        
        try{
        query = "select licencenumber,vehiclename,tour_tourid,driver_driverid from vehicle";
        rs = st.executeQuery(query);
        while(rs.next()){
            int k =0;
            if(k>=0){
                txtlicencenumber.setText(rs.getString("licencenumber"));
                txtvehiclename.setText(rs.getString("vehiclename"));
                int i = rs.getInt("tour_tourid");
                int m = rs.getInt("driver_driverid");
                
                query = "select tourname from tour where tourid='"+i+"'";
                rs = st.executeQuery(query);
                rs.next();
                txttourname.setText(rs.getString("tourname"));
        
                query = "select firstname from driver where driverid='"+m+"'";
                rs = st.executeQuery(query);
                rs.next();
                txtdrivername.setText(rs.getString("firstname"));
            }
            k = k+1;
        }
        }
        catch(SQLException ex){
                ex.printStackTrace();
                }
        
    }//GEN-LAST:event_btnnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbldrivername;
    private javax.swing.JLabel lbllicencenumber;
    private javax.swing.JLabel lbltour;
    private javax.swing.JLabel lblvehiclename;
    private javax.swing.JTextField txtdrivername;
    private javax.swing.JTextField txtlicencenumber;
    private javax.swing.JTextField txttourname;
    private javax.swing.JTextField txtvehiclename;
    // End of variables declaration//GEN-END:variables
}
